### ISSUE TITLE
Code cleanup/comments

### ISSUE THREAD

**Issue by Pai-Sho** [TudorSante/xROOKStrategySnapshot#2]
### **STRATEGY NAME**
Strategy name should be changed to be xROOK specific, as we have an unusual setup where our "staking" contract is actually a liquidity pool originally meant for flash loan and emissions APR. Let's change it to `xrook-balance-of-underlying-weighted`

### **PARAMS**
https://github.com/TudorSante/xROOKStrategySnapshot/blob/5164aacc714654b6046cf3869ceeb7673f89b6f2/src/strategies/erc20-balance-of-staked-multiplier/examples.json#L6
We try to use variable names which are simple, yet fully descriptive. Avoid using abbreviations when possible
- Change `stakingCoeff` to `weight`
- Change `baseStkToken` to `underlyingTokenAddress`
- Change `liqPoolContract` to `liquidityPoolAddress`

### **IMPLEMENTATION**
https://github.com/TudorSante/xROOKStrategySnapshot/blob/5164aacc714654b6046cf3869ceeb7673f89b6f2/src/strategies/erc20-balance-of-staked-multiplier/index.ts#L34
- Change `stkTotalSupply` to `xROOKTotalSupply`

https://github.com/TudorSante/xROOKStrategySnapshot/blob/5164aacc714654b6046cf3869ceeb7673f89b6f2/src/strategies/erc20-balance-of-staked-multiplier/index.ts#L42
- Change `tokenStakedTotalBalance` to `liquidityPoolBalance`

https://github.com/TudorSante/xROOKStrategySnapshot/blob/5164aacc714654b6046cf3869ceeb7673f89b6f2/src/strategies/erc20-balance-of-staked-multiplier/index.ts#L51
- Change `underlyingCoeff` to `underlyingValue`

**General comments:**
For `score` and the final return object, follow the same formatting used in [erc20-balance-of-weighted](https://github.com/snapshot-labs/snapshot-strategies/blob/master/src/strategies/erc20-balance-of-weighted/index.ts)
- Change `score` to `scores`
- Use `Object.entries(scores).map((score) => [score[0], score[1] * underlyingValue * options.weight])`
- Remove all commented out code and `console.log` statements

**Comment by TudorSante** [comment]
Finished implementing the above. Thx!
